// Impect KPI categories, generated from impect_metric_stability/build_position_clusters.py (CATEGORY_CONFIG).
// Equal-weight, direction-consistent z-score categories; every metric belongs to one category per position.
// Regenerate rather than hand-edit if the study changes.

export const POSITION_MAP = {
  GOALKEEPER: "GK", CENTRAL_DEFENDER: "CB", LEFT_WINGBACK_DEFENDER: "FB", RIGHT_WINGBACK_DEFENDER: "FB",
  DEFENSE_MIDFIELD: "DM", CENTRAL_MIDFIELD: "CM", ATTACKING_MIDFIELD: "AM",
  LEFT_WINGER: "W", RIGHT_WINGER: "W", CENTER_FORWARD: "ST",
};

export const POSITION_LABEL = {
  GK: "Goalkeeper", CB: "Centre-Back", FB: "Full-Back", DM: "Defensive Mid",
  CM: "Central Mid", AM: "Attacking Mid", W: "Winger", ST: "Striker",
};

// Match-share floor for the peer cohort (player_percentiles.py uses 5.0).
export const MIN_MATCH_SHARE = 5;

export const CATEGORIES = {
  GK: {
    "Shot-stopping quality": [
      "score__GK_PREVENTED_GOALS_TOTAL_SHOT_XG",
      "score__GK_PREVENTED_GOALS_TOTAL_SHOT_XG_PERCENT",
      "score__GK_PREVENTED_GOALS_TOTAL_POSTSHOT_XG",
      "score__GK_PREVENTED_GOALS_TOTAL_POSTSHOT_XG_PERCENT",
    ],
    "Shot-type save profile": [
      "score__GK_PREVENTED_GOALS_POST_SHOT_XG_BY_ACTION1V1_AGAINST_GK_SHOT_RATIO",
      "score__GK_PREVENTED_GOALS_POST_SHOT_XG_BY_ACTION_CLOSE_RANGE_SHOT_RATIO",
      "score__GK_PREVENTED_GOALS_POST_SHOT_XG_BY_ACTION_HEADER_SHOT_RATIO",
      "score__GK_PREVENTED_GOALS_POST_SHOT_XG_BY_ACTION_LONG_RANGE_SHOT_RATIO",
      "score__GK_PREVENTED_GOALS_POST_SHOT_XG_BY_ACTION_MID_RANGE_SHOT_RATIO",
    ],
    "High-ball command": [
      "score__GK_CAUGHT_HIGH_BALLS_PERCENT",
      "score__GK_CAUGHT_AND_PUNCHED_HIGH_BALLS_PERCENT",
      "kpi__WON_AERIAL_DUELS_DEF",
      "score__RATIO_AERIAL_DUELS_DEFENSIVE",
      "score__DEFENSIVE_HEADER_SCORE",
    ],
    "Sweeping and interventions": [
      "score__GK_DEFENSIVE_TOUCHES_OUTSIDE_OWN_BOX",
      "score__LOOSE_BALL_REGAIN_SCORE",
      "score__INTERCEPTION_SCORE",
      "score__CLEARANCE_SCORE",
      "kpi__BALL_WIN_NUMBER",
      "kpi__PXT_DEFEND",
    ],
    "Short circulation": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Distribution security": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Long distribution and restarts": [
      "score__GK_SUCCESSFUL_LAUNCHES_PERCENT",
      "score__GOAL_KICK_SCORE",
      "score__CHIPPED_PASS_SCORE",
      "score__DIAGONAL_PASS_SCORE",
      "kpi__PXT_SETPIECE_PRO",
    ],
    "Line-breaking distribution": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
  },
  CB: {
    "Build-up circulation": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Line-breaking distribution": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Carrying out of pressure": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Pressing activity": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
    ],
    "Interceptions and recoveries": [
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
      "score__LOOSE_BALL_REGAIN_SCORE",
      "kpi__SECOND_BALL_START",
      "kpi__SECOND_BALL_WIN",
      "score__BLOCK_SCORE",
    ],
    "Ground defending": [
      "kpi__WON_GROUND_DUELS_DEF",
      "kpi__LOST_GROUND_DUELS_DEF",
      "score__RATIO_GROUND_DUELS_DEFENSIVE",
      "score__NUMBER_OF_GROUND_DUELS",
      "score__GROUND_DUEL_SCORE",
    ],
    "Aerial defending": [
      "kpi__WON_AERIAL_DUELS_DEF",
      "kpi__LOST_AERIAL_DUELS_DEF",
      "score__RATIO_AERIAL_DUELS_DEFENSIVE",
      "score__DEFENSIVE_HEADER_SCORE",
      "score__AERIAL_DUELS_NUMBER_IN_PACKING_ZONE_CB",
    ],
    "Set-piece and box threat": [
      "score__OFFENSIVE_HEADER_SCORE",
      "kpi__WON_AERIAL_DUELS_OFF",
      "score__HEADER_SHOT_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
      "kpi__SHOT_XG",
      "kpi__SHOT_AT_GOAL_NUMBER",
    ],
  },
  FB: {
    "Build-up circulation": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Line-breaking progression": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Wide receiving and overlaps": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "score__AVAILABILITY_OUT_WIDE_SCORE",
      "score__AVAILABILITY_FDR_SCORE",
      "kpi__DISTANCE_TO_GOAL_COVERED_FDR",
    ],
    "Carrying and attacking 1v1": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Crossing and chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "score__LOW_CROSS_SCORE",
      "score__HIGH_CROSS_SCORE",
    ],
    "Pressing activity": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
    ],
    "Interceptions and recoveries": [
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
      "score__LOOSE_BALL_REGAIN_SCORE",
      "kpi__SECOND_BALL_START",
      "kpi__SECOND_BALL_WIN",
      "score__BLOCK_SCORE",
    ],
    "Ground defending": [
      "kpi__WON_GROUND_DUELS_DEF",
      "kpi__LOST_GROUND_DUELS_DEF",
      "score__RATIO_GROUND_DUELS_DEFENSIVE",
      "score__NUMBER_OF_GROUND_DUELS",
      "score__GROUND_DUEL_SCORE",
    ],
    "Aerial defending": [
      "kpi__WON_AERIAL_DUELS_DEF",
      "kpi__LOST_AERIAL_DUELS_DEF",
      "score__RATIO_AERIAL_DUELS_DEFENSIVE",
      "score__DEFENSIVE_HEADER_SCORE",
      "score__AERIAL_DUELS_NUMBER_IN_PACKING_ZONE_CB",
    ],
  },
  DM: {
    "Circulation and tempo": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Line-breaking progression": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Receiving and positioning": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING_DUETO_VERIFICATION",
      "score__AVAILABILITY_BTL_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
    ],
    "Chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "kpi__SHOT_XG_FROM_PASSES",
      "kpi__ASSISTS",
    ],
    "Carrying and pressure escape": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Pressing activity": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
    ],
    "Interceptions and recoveries": [
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
      "score__LOOSE_BALL_REGAIN_SCORE",
      "kpi__SECOND_BALL_START",
      "kpi__SECOND_BALL_WIN",
      "score__BLOCK_SCORE",
    ],
    "Ground defending": [
      "kpi__WON_GROUND_DUELS_DEF",
      "kpi__LOST_GROUND_DUELS_DEF",
      "score__RATIO_GROUND_DUELS_DEFENSIVE",
      "score__NUMBER_OF_GROUND_DUELS",
      "score__GROUND_DUEL_SCORE",
    ],
    "Aerial defending": [
      "kpi__WON_AERIAL_DUELS_DEF",
      "kpi__LOST_AERIAL_DUELS_DEF",
      "score__RATIO_AERIAL_DUELS_DEFENSIVE",
      "score__DEFENSIVE_HEADER_SCORE",
      "score__AERIAL_DUELS_NUMBER_IN_PACKING_ZONE_CB",
    ],
  },
  CM: {
    "Circulation and tempo": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security and directness": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Line-breaking progression": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Receiving and movement": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING_DUETO_VERIFICATION",
      "score__AVAILABILITY_BTL_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
    ],
    "Chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "kpi__SHOT_XG_FROM_PASSES",
      "kpi__ASSISTS",
    ],
    "Shooting threat": [
      "kpi__SHOT_AT_GOAL_NUMBER",
      "kpi__SHOT_AT_GOAL_NUMBER_ON_TARGET",
      "kpi__SHOT_XG",
      "kpi__POSTSHOT_XG",
      "kpi__GOALS",
    ],
    "Carrying and attacking 1v1": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Pressing and ball winning": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
    ],
    "Ground duels": [
      "kpi__WON_GROUND_DUELS",
      "kpi__LOST_GROUND_DUELS",
      "score__NUMBER_OF_GROUND_DUELS",
      "score__RATIO_GROUND_DUELS",
      "score__GROUND_DUEL_SCORE",
    ],
    "Aerial duels": [
      "kpi__WON_AERIAL_DUELS",
      "kpi__LOST_AERIAL_DUELS",
      "score__AERIAL_DUELS_NUMBER",
      "score__RATIO_AERIAL_DUELS",
      "score__OFFENSIVE_HEADER_SCORE",
      "score__DEFENSIVE_HEADER_SCORE",
    ],
  },
  AM: {
    "Circulation and link play": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security and directness": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__REVERSE_PLAY_ADDED_OPPONENTS",
      "score__RATIO_REVERSE_PLAY_ADDED_OPPONENTS",
    ],
    "Line-breaking progression": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Receiving and movement": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING_DUETO_VERIFICATION",
      "score__AVAILABILITY_BTL_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
    ],
    "Chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "kpi__SHOT_XG_FROM_PASSES",
      "kpi__ASSISTS",
    ],
    "Shooting threat": [
      "kpi__SHOT_AT_GOAL_NUMBER",
      "kpi__SHOT_AT_GOAL_NUMBER_ON_TARGET",
      "kpi__SHOT_XG",
      "kpi__POSTSHOT_XG",
      "kpi__GOALS",
    ],
    "Finishing quality": [
      "score__RATIO_POSTSHOT_XG_SHOT_XG",
      "score__RATIO_GOALS_SHOT_XG",
      "score__RATIO_GOALS_POSTSHOT_XG",
      "score__RATIO_SHOTS_ON_TARGET",
      "score__RATIO_SHOTS_PER_GOAL",
    ],
    "Carrying and attacking 1v1": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Pressing and ball winning": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
    ],
    "Aerial and physical duels": [
      "kpi__WON_AERIAL_DUELS",
      "score__AERIAL_DUELS_NUMBER",
      "score__RATIO_AERIAL_DUELS",
      "score__NUMBER_OF_GROUND_DUELS",
      "kpi__WON_GROUND_DUELS",
      "score__RATIO_GROUND_DUELS",
    ],
  },
  W: {
    "Circulation and link play": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security and directness": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__REVERSE_PLAY_ADDED_OPPONENTS",
      "score__RATIO_REVERSE_PLAY_ADDED_OPPONENTS",
    ],
    "Line-breaking progression": [
      "kpi__PXT_PASS_PRO",
      "kpi__BYPASSED_DEFENDERS",
      "kpi__BYPASSED_OPPONENTS_MIDFIELD",
      "kpi__BYPASSED_OPPONENTS_WO_VERIFICATION",
      "kpi__BYPASSED_OPPONENTS_RAW",
    ],
    "Receiving and movement": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING_DUETO_VERIFICATION",
      "score__AVAILABILITY_BTL_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
    ],
    "Chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "kpi__SHOT_XG_FROM_PASSES",
      "kpi__ASSISTS",
    ],
    "Shooting threat": [
      "kpi__SHOT_AT_GOAL_NUMBER",
      "kpi__SHOT_AT_GOAL_NUMBER_ON_TARGET",
      "kpi__SHOT_XG",
      "kpi__POSTSHOT_XG",
      "kpi__GOALS",
    ],
    "Finishing quality": [
      "score__RATIO_POSTSHOT_XG_SHOT_XG",
      "score__RATIO_GOALS_SHOT_XG",
      "score__RATIO_GOALS_POSTSHOT_XG",
      "score__RATIO_SHOTS_ON_TARGET",
      "score__RATIO_SHOTS_PER_GOAL",
    ],
    "Carrying and attacking 1v1": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Pressing and ball winning": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
    ],
    "Aerial and physical duels": [
      "kpi__WON_AERIAL_DUELS",
      "score__AERIAL_DUELS_NUMBER",
      "score__RATIO_AERIAL_DUELS",
      "score__NUMBER_OF_GROUND_DUELS",
      "kpi__WON_GROUND_DUELS",
      "score__RATIO_GROUND_DUELS",
    ],
  },
  ST: {
    "Link play and circulation": [
      "score__TOTAL_TOUCHES",
      "score__SUCCESSFUL_PASSES_CLEAN",
      "kpi__EXPECTED_PASSES",
      "score__PASS_COMPLETION_OVER_EXPECTED",
      "score__RATIO_PASSING_ACCURACY",
    ],
    "Ball security": [
      "kpi__BALL_LOSS_NUMBER",
      "kpi__CRITICAL_BALL_LOSS_NUMBER",
      "score__UNSUCCESSFUL_PASSES_CLEAN",
      "kpi__PXT_PASS_FAIL",
      "kpi__BALL_LOSS_ADDED_OPPONENTS",
    ],
    "Receiving and box movement": [
      "kpi__PXT_REC",
      "kpi__BYPASSED_DEFENDERS_RECEIVING",
      "kpi__BYPASSED_OPPONENTS_RECEIVING",
      "score__AVAILABILITY_BTL_SCORE",
      "score__AVAILABILITY_FDR_SCORE",
      "score__AVAILABILITY_IN_THE_BOX_SCORE",
    ],
    "Hold-up play and ground duels": [
      "score__HOLD_UP_PLAY_SCORE",
      "kpi__WON_GROUND_DUELS_OFF",
      "kpi__LOST_GROUND_DUELS_OFF",
      "score__RATIO_GROUND_DUELS_OFFENSIVE",
      "score__NUMBER_OF_GROUND_DUELS",
      "kpi__NUMBER_OF_FOULS_WON",
    ],
    "Chance creation": [
      "kpi__EXPECTED_SHOT_ASSISTS",
      "kpi__SHOT_ASSISTS",
      "kpi__SHOT_CREATING_ACTIONS",
      "kpi__EXPECTED_GOAL_ASSISTS",
      "kpi__SHOT_XG_FROM_PASSES",
      "kpi__ASSISTS",
    ],
    "Shooting threat": [
      "kpi__SHOT_AT_GOAL_NUMBER",
      "kpi__SHOT_AT_GOAL_NUMBER_ON_TARGET",
      "kpi__SHOT_XG",
      "kpi__POSTSHOT_XG",
      "kpi__GOALS",
    ],
    "Finishing quality": [
      "score__RATIO_POSTSHOT_XG_SHOT_XG",
      "score__RATIO_GOALS_SHOT_XG",
      "score__RATIO_GOALS_POSTSHOT_XG",
      "score__RATIO_SHOTS_ON_TARGET",
      "score__RATIO_SHOTS_PER_GOAL",
    ],
    "Carrying and attacking 1v1": [
      "kpi__DISTANCE_TO_GOAL_COVERED_DRIBBLE",
      "kpi__PXT_DRIBBLE",
      "kpi__PXT_DRIBBLE_PRO",
      "score__DRIBBLE_SCORE",
    ],
    "Pressing and ball winning": [
      "kpi__NUMBER_OF_PRESSES",
      "kpi__NUMBER_OF_PRESSES_BUILD_UP",
      "kpi__NUMBER_OF_PRESSES_BETWEEN_THE_LINES",
      "kpi__NUMBER_OF_PRESSES_COUNTER_PRESS",
      "kpi__BALL_WIN_NUMBER",
      "score__INTERCEPTION_SCORE",
    ],
    "Aerial target play": [
      "kpi__WON_AERIAL_DUELS_OFF",
      "kpi__LOST_AERIAL_DUELS_OFF",
      "score__RATIO_AERIAL_DUELS_OFFENSIVE",
      "score__AERIAL_DUELS_NUMBER",
      "score__OFFENSIVE_HEADER_SCORE",
      "score__HEADER_SHOT_SCORE",
    ],
  },
};

export const ALL_METRICS = [...new Set(Object.values(CATEGORIES).flatMap((c) => Object.values(c).flat()))];
